services:
  django:
    container_name: django-backend
    build:
      context: ./django-backend
    working_dir: /app/BankApp
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django-backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=BankApp.settings
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: django_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
      
  react:
    container_name: react-frontend
    build:
      context: ./react-frontend
    command: npx expo start --tunnel
    volumes:
      - ./react-frontend:/app
      - /app/node_modules
    ports:
      - "19006:19006"
      - "8081:8081"
    environment:
    - EXPO_PUBLIC_API_URL=http://django-backend:8000
    - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0


volumes:
  postgres_data:
